export const SET_USER_SUCCESS = 'SET_USER_SUCCESS';
export const SET_USER_ERROR = 'SET_USER_ERROR';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_ERROR = 'FETCH_USER_ERROR';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_ERROR = 'UPDATE_USER_ERROR';
export const AUTH_USER_SUCCESS = 'AUTH_USER_SUCCESS';
export const AUTH_USER_ERROR = 'AUTH_USER_ERROR';
export const CLEAR_USER = 'CLEAR_USER';
export const USER_LOADER = 'USER_LOADER';

export const FORM_SUBMIT_SUCCESS = 'FORM_SUBMIT_SUCCESS';
export const FORM_SUBMIT_ERROR = 'FORM_SUBMIT_ERROR';
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_DATA_ERROR  = 'FETCH_DATA_ERROR ';
export const UPDATE_FORM_SUCCESS = 'UPDATE_FORM_SUCCESS';
export const UPDATE_FORM_ERROR = 'UPDATE_FORM_ERROR';
export const DELETE_FORM_SUCCESS = 'DELETE_FORM_SUCCESS';
export const DELETE_FORM_ERROR = 'DELETE_FORM_ERROR';
export const SET_FORMS = 'SET_FORMS';

export const SIDEBAR_COLLAPSED = 'SIDEBAR_COLLAPSED';

export const FORM_CONFIG_SUCCESS = 'FORM_CONFIG_SUCCESS';
export const FORM_CONFIG_ERROR = 'FORM_CONFIG_ERROR';
export const FETCH_CONFIG_SUCCESS = 'FETCH_CONFIG_SUCCESS';
export const FETCH_CONFIG_ERROR = 'FETCH_CONFIG_ERROR';
export const GET_CONFIG_FORMS = 'GET_CONFIG_FORMS';
export const UPDATE_CONFIG_SUCCESS = 'UPDATE_CONFIG_SUCCESS';
export const UPDATE_CONFIG_ERROR = 'UPDATE_CONFIG_ERROR';
export const DELETE_CONFIG_SUCCESS = 'DELETE_CONFIG_SUCCESS';
export const DELETE_CONFIG_ERROR = 'DELETE_CONFIG_ERROR';
export const VALUE_CONFIG_SUCCESS = 'VALUE_CONFIG_SUCCESS';
export const VALUE_CONFIG_ERROR = 'VALUE_CONFIG_ERROR';
export const UPDATE_VALUE_SUCCESS = 'UPDATE_VALUE_SUCCESS';
export const UPDATE_VALUE_ERROR = 'UPDATE_VALUE_ERROR';
export const DELETE_VALUE_SUCCESS = 'DELETE_VALUE_SUCCESS';
export const DELETE_VALUE_ERROR = 'DELETE_VALUE_ERROR';

export const ADD_EVENT_SUCCESS = 'ADD_EVENT_SUCCESS';
export const FETCH_EVENT_SUCCESS = 'FETCH_EVENT_SUCCESS';
export const FETCH_EVENT_LOADER = 'FETCH_EVENT_LOADER';
export const UPDATE_EVENT_SUCCESS = 'UPDATE_EVENT_SUCCESS';
export const FETCH_EVENTDATA_SUCCESS = 'FETCH_EVENTDATA_SUCCESS';
export const FETCH_UPDATE_EVENT_LOADER = 'FETCH_UPDATE_EVENT_LOADER';
export const DELETE_EVENT_SUCCESS = 'DELETE_EVENT_SUCCESS';